### ISSUE TITLE
Comando "hentai"

### ISSUE THREAD

**Issue by arthurrochat** [jsepdro/uiuiTRON2000#1]
Comando "hentai" exibe um texto incorreto e sem nexo.

**Comment by guias12** [comment]
também reparei isso enquanto testava o software, um erro assim é bastante grave e exige um reparo por parte do desenvolvedor @jsepdro

**Comment by victorandradeap** [comment]
O problema ainda não foi corrigido, talvez se nós mesmo corrigirmos esse bug seria melhor.
Oq diz @jsepdro , posso abrir o pull request sem problemas.

**Comment by jsepdro** [comment]
Os senhores estão desviando o foco do verdadeiro problema que é a perda da conexão com a API do Spotify após um tempo sem uso.

**Comment by guias12** [comment]
Suponho que deve existir algum método pra fechar conexão nessa biblioteca que você tá usando, também suponho que se você só abrir a conexão quando for usar ela, e fechar sempre quando não for usar deve acabar com esse problema.

**Comment by victorandradeap** [comment]
> Os senhores estão desviando o foco do verdadeiro problema que é a perda da conexão com a API do Spotify após um tempo sem uso.

Acredito que para tratar tal problema o correto seria criar outra issue, o foco desta aqui é outro.

**Comment by jsepdro** [comment]
O comando foi atualizado para ser condizente com a realidade. Não recomendo mais a utilização do mesmo, usem por conta própria
